<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27991" started-at="2018-08-12T13:15:02Z" finished-at="2018-08-12T13:15:30Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="27991" started-at="2018-08-12T13:15:02Z" finished-at="2018-08-12T13:15:30Z">
      <class name="com.testng.LoginTest">
        <test-method status="PASS" signature="Browser()[pri:0, instance:com.testng.LoginTest@19d37183]" name="Browser" is-config="true" duration-ms="11098" started-at="2018-08-12T13:15:02Z" finished-at="2018-08-12T13:15:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Browser -->
        <test-method status="PASS" signature="enter_wrong_email()[pri:0, instance:com.testng.LoginTest@19d37183]" name="enter_wrong_email" duration-ms="1085" started-at="2018-08-12T13:15:13Z" finished-at="2018-08-12T13:15:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_wrong_email -->
        <test-method status="PASS" signature="close_Browser()[pri:0, instance:com.testng.LoginTest@19d37183]" name="close_Browser" is-config="true" duration-ms="1349" started-at="2018-08-12T13:15:14Z" finished-at="2018-08-12T13:15:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_Browser -->
        <test-method status="PASS" signature="Browser()[pri:0, instance:com.testng.LoginTest@19d37183]" name="Browser" is-config="true" duration-ms="8537" started-at="2018-08-12T13:15:16Z" finished-at="2018-08-12T13:15:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Browser -->
        <test-method status="FAIL" signature="enter_wrong_password()[pri:0, instance:com.testng.LoginTest@19d37183]" name="enter_wrong_password" duration-ms="4857" started-at="2018-08-12T13:15:24Z" finished-at="2018-08-12T13:15:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Password Error] but found [Wrong password. Try again or click Forgot password to reset it.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Password Error] but found [Wrong password. Try again or click Forgot password to reset it.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.LoginTest.enter_wrong_password(LoginTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_wrong_password -->
        <test-method status="PASS" signature="close_Browser()[pri:0, instance:com.testng.LoginTest@19d37183]" name="close_Browser" is-config="true" duration-ms="1033" started-at="2018-08-12T13:15:29Z" finished-at="2018-08-12T13:15:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_Browser -->
      </class> <!-- com.testng.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
